### ISSUE TITLE
Add a tlsverify option to disable certificate validation

### ISSUE THREAD

**Issue by dcolens** [cloudimmunity/docker-slim#16]
Because of VPN software I redirect the docker port to localhost, which causes the certificate validation to fail. It is easy to workaround with `docker --tlsverify=false`, could you implement a similar option for docker-slim ?

**Comment by kcq** [comment]
Definitely yes and hopefully very soon :-)

**Comment by kcq** [comment]
The latest release (v1.13) should provide what you need. If you using the Docker environment variables you can add "--tls-verify=false" when you run "docker-slim". Take a look at the Docker Connect Options section in the README file for more details.
