### ISSUE TITLE
Silent mode?

### ISSUE THREAD

**Issue by lechen26** [cloudimmunity/docker-slim#18]
Hi

is there any silent or non interactive mode? to create a slim image without needing to press enter?

thanks
chen

**Comment by kcq** [comment]
Yes :-) You can use the "--continue-after" build option. The "probe" value is good when you use the HTTP probe feature to interact with your image. That way DockerSlim will wait for the probe to finish and then it'll continue minifying the image. You can use a "timeout" instead. It defaults to 60 seconds, but you can specify a custom timeout by passing the number of seconds you want to wait. You can also signals if you pick the "signal" value. Send the USR1 signal to the DockerSlim process.

Soon there'll be an HTTP server mode too, so you'll be able to control DockerSlim using HTTP API calls.

**Comment by vraravam** [comment]
How can i specify the `timeout` value? An example of this would be greatly appreciated!

**Comment by kcq** [comment]
The command should look something like this `docker-slim build --continue-after=30 --http-probe-off my-api`. I assume `my-api` is a containerized CLI app. It makes sense to have a mode to continue once the app exits without waiting any extra time.

**Comment by vraravam** [comment]
Thanks @kcq - I was trying with a value of `0` (intending for fully non-interactive mode, but that reverts back to waiting for user input. Instead, `1` works perfectly fine!

`my-app` is an image for a java springboot application whose `ENTRYPOINT` is `java -jar ...` so, it'll not exit per se

**Comment by kcq** [comment]
@vraravam you don't want to turn off http probing then because one way or another the app needs to have a chance to fully initialize, which may take a bit longer than usual because the app is traced. With the default http probe (which you get if you don't set any extra params) your app will get pinged with `GET /` and the probe will keep trying until it gets a response or it runs out of the number of retries it uses. If your springboot app has a different root path you'll want to specify a custom http probe command like this `--http-probe-cmd /your/app/root`.

**Comment by vraravam** [comment]
Thanks @kcq - but, while building the image, i fail to understand why i need the app to fully initialize. Could you please elaborate? I can understand if running, but, while building?

**Comment by kcq** [comment]
@vraravam the `build` command in `docker-slim` performs static and dynamic analysis on the target container images and it ends up creating an ephemeral container to do the dynamic analysis and that's where the probes are used.

**Comment by vraravam** [comment]
sorry to belabor the point, but what's the use of dynamic analysis? Is it for cases where the app writes files to some disk location or other similar functionality?

**Comment by kcq** [comment]
Dynamic analysis is necessary to understand the containerized application and what it needs. The information collected during dynamic analysis is augmented with the information collected with static analysis and all that is used to generate the minified image. Without that information you'll have to use a lot of `--include-***` parameters to explicitly declare what you want to keep when it comes to the system dependencies.
