### ISSUE TITLE
create detailed build instructions

### ISSUE THREAD

**Issue by lkwg82** [cloudimmunity/docker-slim#3]
I'm not familiar with the go build process and like to try your tool as an user.

Would you be so kind and provide detailed build instructions maybe as a docker file!

Thx!

**Comment by kcq** [comment]
A Dockerfile to build the tool is a great idea! Yes, the build instructions definitely need to be expanded.

**Comment by kcq** [comment]
Hopefully the updated build instructions are ok. I also added a Dockerfile to build docker-slim if it works better for you. Let me know if it doesn't work or something doesn't make sense :)

**Comment by lkwg82** [comment]
Sorry for my late reply, I did not find time earlier.

This Dockerfile is a good start. But I dont know which command to invoke to get binaries built.

My suggestions for some details build instruction:

```docker
FROM golang:1.4

RUN go get github.com/mitchellh/gox && \
        gox -build-toolchain -os="linux" -os="darwin"

ADD .   /build
WORKDIR /build
```

build instructions should be:
```bash
docker build -t docker-slim .
docker run -ti docker-slim './src.build.sh' 
```
Then you can find the binaries in ...


This what I expect. I'm completely new to your build process.
Do you understand me?

Cheers Lars
