### ISSUE TITLE
please upload ready to use docker images to Docker Hub

### ISSUE THREAD

**Issue by sandys** [cloudimmunity/docker-slim#4]
Could you upload a few of your images to Docker Hub please.

**Comment by sandys** [comment]
it will be interesting to see how small can something like https://github.com/micahhausler/container-transform get to.

`docker pull ambition/container-transform:latest
`

**Comment by kcq** [comment]
Thank you for the idea! Shouldn't take too long to do :) And it'll try to build and publish a minified version of the container-transform tool too.

**Comment by kcq** [comment]
Here's a DockerSlim'ed version: https://hub.docker.com/r/dslim/container-transform.slim/

Note that the official DockerHub version from ambition is old(er) and it's based on Python 2.7. The current version is based on python 3.5. 'container-transform.slim' is built from the latest 1.0.0 release.

**Comment by kcq** [comment]
If you have any other suggestions feel free to open another ticket!

**Comment by sandys** [comment]
Erm... This is a minified version of the tool itself, which is great.. But
I think most people want to test out a minified python or  nodejs or ruby
container.
