### ISSUE TITLE
Doesn't build on Ubuntu 14.04

### ISSUE THREAD

**Issue by pggsx** [cloudimmunity/docker-slim#7]
Currently attempting to run docker-slim and docker-slim-sensor on Ubuntu and I've gotten 
"bash :./docker-slim: cannot execute binary file: Exec format error" 
Is there anyway to convert the Mac binary to be compatible with Linux?

**Comment by kcq** [comment]
The released binaries are for Macs. You can build it for Linux too. The command to do that is commented out in scripts/src.build.sh (gox -osarch="linux/amd64" -output="$BDIR/bin/linux/docker-slim").

If you are ok with waiting a bit the next release binaries will include Linux versions too.

**Comment by pggsx** [comment]
Oh, wow sorry about thanks for the tip. Just out of curiosity how long is going to be till the next release. Also, I would be willing to help if you need someone for go stuff :)

**Comment by kcq** [comment]
The next release will be done by the end of this weekend. However, I also updated the current release to include Linux binaries: https://github.com/cloudimmunity/docker-slim/releases/download/1.11/dist_linux.zip

Yes, it'll be great if you could help. What would you like to do? Any preferences or ideas?

**Comment by pggsx** [comment]
hey sorry about the late response but what would you need done? I'm pretty much getting into go myself and I would like to help with anything. So, what can I do for you?
