### ISSUE TITLE
Linux binaries: workdir requires one argument

### ISSUE THREAD

**Issue by pggsx** [cloudimmunity/docker-slim#8]
Thanks for the updated linux binaries!After running the ./docker-slim build <container id> command, the build and profile was process was successful, however when building the slim profile, a docker error occurred stating that WORKDIR requires one argument. 
Error output:
INFO[0028] docker-slim: building 'slim' image...        
Step 1 : FROM scratch
 ---> 
Step 2 : COPY files /
 ---> Using cache
 ---> cbd64cd3ed44
Step 3 : WORKDIR 
FATA[0052] docker-slim: failure error=WORKDIR requires exactly one argument

Thanks,
pggsx

**Comment by kcq** [comment]
Sorry to hear about that and thanks for reporting it. Can you share Dockerfile and Dockerfile.fat  files from the  .images/<YOUR_TARGET_IMAGE_ID>/artifacts directory? Just the WORKDIR lines from those two files will be fine. If they contain sensitive info can you send the info to me directly (obfuscating the sensitive info).

What version of Docker are you using?

**Comment by pggsx** [comment]
Yea no problem. I'm currently running Docker version 1.10. Can I send it to you later on this morning since its about 12:00am here on the east coast. Also, I'm still interested in helping out with docker-slim with pretty much anything. Feel free to let me know what I can do =]

**Comment by pggsx** [comment]
Hey, here's the zip, theres no code since it didn't get that far 
Please let me know about potential options

[dockerfiles.zip](https://github.com/cloudimmunity/docker-slim/files/121989/dockerfiles.zip)
Thanks,

pggsx

**Comment by geekthattweaks** [comment]
I have the same issue.

docker version:
Client:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.0
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   590d5108
 Built:        Thu Feb  4 18:36:33 2016
 OS/Arch:      linux/amd64

`Dockerfile:
FROM scratch
COPY files /
WORKDIR
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV REFRESHED_AT 2015-10-30
ENTRYPOINT ["/root/ReRun","/root/run.json"]`

```
Dockerfile.fat
# new image
ADD file:8e4943cd86e9b2ca1333aac03503cb942f93dad4c3f6be8457787368c9213513 in /
RUN echo '#!/bin/sh' > /usr/sbin/policy-rc.d && \
        echo 'exit 101' >> /usr/sbin/policy-rc.d && \
        chmod +x /usr/sbin/policy-rc.d && \
        dpkg-divert --local --rename --add /sbin/initctl && \
        cp -a /usr/sbin/policy-rc.d /sbin/initctl && \
        sed -i 's/^exit.*/exit 0/' /sbin/initctl && \
        echo 'force-unsafe-io' > /etc/dpkg/dpkg.cfg.d/docker-apt-speedup && \
        echo 'DPkg::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };' > /etc/apt/apt.conf.d/docker-clean && \
        echo 'APT::Update::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };' >> /etc/apt/apt.conf.d/docker-clean && \
        echo 'Dir::Cache::pkgcache ""; Dir::Cache::srcpkgcache "";' >> /etc/apt/apt.conf.d/docker-clean && \
        echo 'Acquire::Languages "none";' > /etc/apt/apt.conf.d/docker-no-languages && \
        echo 'Acquire::GzipIndexes "true"; Acquire::CompressionTypes::Order:: "gz";' > /etc/apt/apt.conf.d/docker-gzip-indexes
RUN sed -i 's/^#\s*\(deb.*universe\)$/\1/g' /etc/apt/sources.list
CMD ["/bin/bash"]
MAINTAINER NodeCraft
ENV REFRESHED_AT=2015-10-30
RUN apt-get update && \
        apt-get install -y --no-install-recommends      ca-certificates         curl && \
        rm -rf /var/lib/apt/lists/*
COPY file:b5cadbbfb2b44c48437918c4eb584496e99c72bd6dee0db1fc75e76becef4c1e in /root/ReRun
COPY file:d9d217307011be2e02c9eb33c7a0b2b0407a3082f73f35eb196d46147b065fb2 in /root/run.json
RUN chmod +x /root/ReRun
ENTRYPOINT ["/root/ReRun" "/root/run.json"]
# end of image:

**Comment by kcq** [comment]
Thank you guys! An empty WORKDIR is the reason for this buy.

**Comment by kcq** [comment]
@geekthattweaks / @pggsx , it should be fixed now. I updated the latest release binaries to include the fix. Give it another try and let me know if you still have problems.

**Comment by geekthattweaks** [comment]
This seems to be working fine now. Thanks for the quick fix!

**Comment by pggsx** [comment]
Soo, it built an images, however when I ran the image, I basically just got a bash shell, with limited functionality. Currently, I am only able to do pwd and cd. No ls or any other functionality. In addition, the only directories,I have are /bin /dev /etc /lib /lib64 /proc /sys /usr
My original images contained a user as well as other files located on the docker images itself. Is this a bug-related issue or just an implementation design choice

**Comment by kcq** [comment]
@pggsx Pavan, can you describe your original image, what it does, and what's in it? Is it an image for a specific application or is it a generic dev image? In the generated Dockerfile.fat file I noticed the "RoRDev" comment...

The current design strips everything that's not used when you create a container from your image. That means if you wanted/needed shell access to the minified image instance/container then you're out of luck. Future versions will allow you to specify a flag to keep your shell though it'll increase the image size, of course.

I'd love to learn more about your image!

**Comment by pggsx** [comment]
Hey, yea it wasn't specifically with my RoRDev image, rather just a plain debian images that I installed git mercurial and a few other tools on. I can send you the dockerfile that its based on

**Comment by pggsx** [comment]
Here's the artifacts folder from when I "slimmed" it down
[Uploading artifacts.zip…]()

**Comment by kcq** [comment]
Thank you! This definitely gives more context. Yes, it's a slightly different use case. The original DockerSlim design wasn't meant to cover it. It doesn't mean it can't in the future :-) DockerSlim will need to support custom user defined slimming instructions to support more advanced use cases. In the meantime, you can take a look at the strip-docker-image tool: https://github.com/mvanholsteijn/strip-docker-image It might help with the image you have.

**Comment by kcq** [comment]
By the way, now (version 1.14+) you can add extra files and directories in your minified images. The "--include-path" option (you can specify more than one). Here's an example: "docker-slim build --http-probe --include-path /some/path/one --include-path /some/dir/file your/image-name"
